#!/bin/bash
#SBATCH --job-name=multimedbench
#SBATCH --output=multimedbench.out
#SBATCH --cpus-per-task=4
#SBATCH --mem=128G
#SBATCH --time=10:00:00

# Your commands here
source ~/data/miniconda3/etc/profile.d/conda.sh

conda activate multimedbench

nvidia-smi

python testTasks.py